### ISSUE TITLE
Bug: case mismatch between source-config.yaml and pipeline activity

### ISSUE THREAD

**Issue by geardleyTC** [jenkins-x-plugins/jx-slack#31]
It seems that pipeline activity is always lower case BUT when owner or repo name is populated into source config it could be mixed case. This causes jx-slack from being able to properly find config and post messages. The workaround is to manually adjust source-config.yaml and make owner/repo lowercase.

I'm not sure if this is a bug for jx-slack or perhaps with how source-config gets populated?

**Comment by cpsburca** [comment]
any updates here, it's frustrating that the configuration is case sensitive. Basically if I change the source-config.yaml to lower case the pipelines stop working. It will be great if we will have an answer here with an workaround or a fix.

**Comment by hervelemeur** [comment]
Related: https://github.com/jenkins-x-plugins/jx-gitops/pull/768
